# Generated by Django 4.1 on 2022-09-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fsq_id', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.TextField()),
                ('country', models.TextField()),
                ('region', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
    ]
